# -*- ruby -*-

require 'rubygems'
require 'hoe'

# Hoe.plugin :compiler
# Hoe.plugin :gem_prelude_sucks
# Hoe.plugin :inline
# Hoe.plugin :racc
# Hoe.plugin :rubyforge
Hoe.plugin :gemcutter

Hoe.spec 'capistrano-ext-params' do
  developer('Andrew Nutter-Upham', 'andynu@.com')

  # self.rubyforge_name = 'capistrano-ext-paramsx' # if different than 'capistrano-ext-params'
end

# vim: syntax=ruby
